ruby overtime.rb incubator sah ./json/sah.json
ruby overtime.rb incubator uig ./json/uig.json
ruby overtime.rb incubator crh ./json/crh.json
ruby overtime.rb incubator tyv ./json/tyv.json
ruby overtime.rb incubator aze ./json/aze.json
ruby overtime.rb languages chv ./json/chv.json
ruby overtime.rb languages tat ./json/tat.json
ruby overtime.rb languages tur ./json/tur.json
ruby overtime.rb languages kum ./json/kum.json
ruby overtime.rb languages kaa ./json/kaa.json
ruby overtime.rb languages uzb ./json/uzb.json
ruby overtime.rb languages bak ./json/bak.json
ruby overtime.rb languages nog ./json/nog.json
ruby overtime.rb languages tuk ./json/tuk.json
ruby overtime.rb languages kaz ./json/kaz.json
