ruby overtime.rb incubator sah | tee ./json/sah.json
ruby overtime.rb incubator uig | tee ./json/uig.json
ruby overtime.rb incubator crh | tee ./json/crh.json
ruby overtime.rb incubator tyv | tee ./json/tyv.json
ruby overtime.rb incubator aze | tee ./json/aze.json
ruby overtime.rb languages chv | tee ./json/chv.json
ruby overtime.rb languages tat | tee ./json/tat.json
ruby overtime.rb languages tur | tee ./json/tur.json
ruby overtime.rb languages kum | tee ./json/kum.json
ruby overtime.rb languages kaa | tee ./json/kaa.json
ruby overtime.rb languages uzb | tee ./json/uzb.json
ruby overtime.rb languages bak | tee ./json/bak.json
ruby overtime.rb languages nog | tee ./json/nog.json
ruby overtime.rb languages tuk | tee ./json/chv.json
ruby overtime.rb languages kaz | tee ./json/kaz.json
